config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :riders,  only: [:index, :show]
  resources :contests, only: [:new, :create]
  get "/contests", to: "contests#new"
  get "/photos", to: "pages#photos"
  get "/locations", to: "pages#locations"
  get "/thankyou", to: "pages#thankyou"

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contest.rb
class Contest < ApplicationRecord
  validates :fname, presence: true, length: { maximum: 25 }
  validates :lname, presence: true, length: { maximum: 25 }
  validates :email, presence: true, length: { maximum: 25 }, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :slogan, presence: true, length: { maximum: 50 }
end

app/models/rider.rb
class Rider < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def new
    @contest = Contest.new
  end

  def create
    @contest = Contest.new(contest_params)

    if @contest.save
      redirect_to thankyou_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  private
  def contest_params
    params.require(:contest).permit(:fname, :lname, :email, :slogan)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def photos
    flickr= Flickr.new "eec935e4108558f22596a8c810b943f3", "12b5c3d7178a1c69"

    args = {
      tags: "BoulderBikeTour,bikerace",
      per_page: 42,
      page: params[:id]
    }

    @photos = []
    flickr.photos.search(args).each do |photo|
      @photos << Flickr.url(photo)
    end

    current_param_id = params[:id].to_i
    if current_param_id > 1
      @page_id_prev = current_param_id - 1
      @page_id_next = current_param_id + 1
    else
      @page_id_next = 2
    end
  end

  def locations
    file_path = Rails.root.join('config', 'google-maps-api.key')

    if File.exist?(file_path)
      File.open(file_path, 'r') do |file|
        # Read the content of the file (assuming it contains only one line)
        @MAP_API_SECRET = file.readline.strip
      end
    end

    @riders_info = Rider.all.map do |rider|
      {
        'fname': rider.fname,
        'lname': rider.lname,
        'lat': rider.latitude,
        'long': rider.longitude,
        'url': rider_path(rider)
      }
    end

    def thankyou
    end

  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  def index
    @riders = Rider.all
  end

  def show
    @rider = Rider.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/views/contests/new.html.erb
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="countdown-container">
          <p class="h1">Share Your Slogan!</p>
          <p class="text-faded">Pedal Your Creativity</p>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container-fluid p-0 mb-2">
  <div class="form-container p-5">
    <h1 class="text-center pb-4">Share Your Slogan for the Boulder Bike Race!</h1>
    <%= form_with(model: @contest, local: true, id: "form") do |form| %>
      <div class="form-group">
        <%= form.label :fname, "First Name:" %>
        <%= form.text_field :fname, class: "form-control" %>
        <% if @contest.errors[:fname].any? %>
          <span class="text-danger">*<%= @contest.errors[:fname][0] %></span>
        <% end %>
      </div>
      <div class="form-group">
        <%= form.label :lname, "Last Name:" %>
        <%= form.text_field :lname, class: "form-control" %>
        <% if @contest.errors[:lname].any?%>
          <span class="text-danger">*<%= @contest.errors[:lname][0] %></span>
        <% end %>
      </div>
      <div class="form-group">
        <%= form.label :email, "Email:" %>
        <%= form.email_field :email, class: "form-control" %>
        <% if @contest.errors[:email].any? %>
          <span class="text-danger">*<%= @contest.errors[:email][0] %></span>
        <% end %>
      </div>
      <div class="form-group">
        <%= form.label :slogan, "Slogan:" %>
        <%= form.text_area :slogan, class: "form-control" %>
        <% if @contest.errors[:slogan].any? %>
          <span class="text-danger">*<%= @contest.errors[:slogan][0] %></span>
        <% end %>
      </div>
      <%= form.submit "Submit", class: "btn btn-primary w-100" %>
    <% end %>
  </div>
</div>



<% content_for :page_specific_js do %>
  <% if @contest.errors.any? %>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const formElement = document.querySelector('#form');
            formElement.scrollIntoView({ behavior: 'smooth' });
        });
    </script>
  <% end %>
<% end %>

app/views/layouts/_info_card.html.erb
<!-- Required parameters:
     - title_upper: The upper part of the section heading
     - body_text: The main body text of the section
-->
<!-- Optional parameters:
     - title_lower: The lower part of the section heading
     - cta_btn_text: Text for the call-to-action button
     - cta_btn_link: URL link for the call-to-action button
     - button_size: size of the cta button (accepted: xl | s)
     - btn_type: bootstrap button classes  (eg. primary, secondary, outline-primary)
-->
<%# locals: (title_upper:, body_text:, title_lower: nil, cta_btn_text: nil, cta_btn_link: nil, button_size: 'xl', btn_type: 'primary') -%>

<div class="intro-text left-0 text-center bg-faded p-5 rounded">
  <h2 class="section-heading mb-4">
    <span class="section-heading-upper"><%= title_upper %></span>
    <% if title_lower %>
      <span class="section-heading-lower"><%= title_lower %></span>
    <% end %>
  </h2>
  <p class="mb-3"><%= simple_format(body_text) %></p>
  <% if cta_btn_text %>
    <div class="intro-button mx-auto">
      <%= link_to cta_btn_text, cta_btn_link, class: "btn btn-#{btn_type} btn-#{button_size}" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoulderBikeRace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= yield :page_specific_js %>
    <%= javascript_importmap_tags  %>
  </head>

  <body>
  <header>
    <h1 class="site-heading text-center text-faded d-none d-lg-block">
      <span class="site-heading-upper mb-3">Racing Through the Rockiess</span>
      <span class="site-heading-lower">Boulder bike race</span>
    </h1>
  </header>
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <%= link_to "Boulder bike race", root_path, class: "navbar-brand text-uppercase fw-bold d-lg-none" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item px-lg-4"><%= link_to "Home", root_path, class: "nav-link text-uppercase" %></li>
          <li class="nav-item px-lg-4"><%= link_to "Photos", photos_path, class: "nav-link text-uppercase" %></li>
          <li class="nav-item px-lg-4"><%= link_to "Location", locations_path, class: "nav-link text-uppercase" %></li>
          <li class="nav-item px-lg-4"><%= link_to "Riders", riders_path, class: "nav-link text-uppercase" %></li>
          <li class="nav-item px-lg-4"><%= link_to "Contest", contests_path, class: "nav-link text-uppercase" %></li>
        </ul>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
  <footer class="footer text-faded text-center py-5">
    <div class="container"><p class="m-0 small">Copyright &copy; Michele Rusticucci 2023</p></div>
  </footer>
</html>

app/views/pages/home.html.erb
<section class="page-section clearfix">
  <div class="container">
    <div class="intro">
      <%= image_tag('intro.jpg', class: 'intro-img img-fluid mb-3 mb-lg-0 rounded') %>
      <%= render partial: "layouts/info_card", locals: {
        title_upper: 'What is about',
        title_lower: 'The race',
        body_text: "The Boulder Bike Race is an annual cycling event set against the breathtaking backdrop of Boulder, Colorado. This thrilling race attracts cyclists of all levels, from seasoned professionals to enthusiastic amateurs, who converge on the scenic city to test their skills and endurance. Held on April 1st each year, participants navigate through challenging terrain, including rolling hills, winding roads, and scenic trails, showcasing the natural beauty of the Rocky Mountains. With its vibrant atmosphere and competitive spirit, the Boulder Bike Race promises an exhilarating experience for riders and spectators alike, celebrating the joy of cycling and the spirit of community in one of America's most picturesque locations.",
        cta_btn_text: 'Send your slogan!',
        cta_btn_link: new_contest_path
      } %>
    </div>
  </div>
</section>
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="countdown-container">
          <p class="h1">Gear up for the Ride!</p>
          <div id="countdown">
            <ul>
              <li><span id="days"></span>days</li>
              <li><span id="hours"></span>Hours</li>
              <li><span id="minutes"></span>Minutes</li>
              <li><span id="seconds"></span>Seconds</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<% content_for :page_specific_js do %>
  <%= javascript_include_tag "customizations/countdown-timer" %>
<% end %>

app/views/pages/location.html.erb
<!-- Include the polyfill script -->
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="countdown-container">
          <p class="h1">Explore Our Riders' Journey!</p>
          <p class="text-faded">Track Every Turn with us</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- The div element for the map -->
<div id="map" class="mb-5"></div>




<% content_for :page_specific_js do %>
  <script>(g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})
  ({key: "<%= @MAP_API_SECRET %>", v: "weekly"});

  const rider_info = [
  <% @riders_info.each do |rider| %>
      {
          'fname': '<%= rider[:fname] %>',
          'lname': '<%= rider[:lname] %>',
          'lat': <%= rider[:lat] %>,
          'long': <%= rider[:long] %>,
          'url':'<%= rider[:url] %>'
      },
  <% end %>
  ]

  </script>

  <%= javascript_include_tag "customizations/maps" %>
<% end %>

app/views/pages/locations.html.erb
<!-- Include the polyfill script -->
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="countdown-container">
          <p class="h1">Explore Our Riders' Journey!</p>
          <p class="text-faded">Track Every Turn with us</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- The div element for the map -->
<div id="map" class="mb-5"></div>




<% content_for :page_specific_js do %>
  <script>(g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})
  ({key: "<%= @MAP_API_SECRET %>", v: "weekly"});

  const rider_info = [
  <% @riders_info.each do |rider| %>
      {
          'fname': '<%= rider[:fname] %>',
          'lname': '<%= rider[:lname] %>',
          'lat': <%= rider[:lat] %>,
          'long': <%= rider[:long] %>,
          'url':'<%= rider[:url] %>'
      },
  <% end %>
  ]

  </script>

  <%= javascript_include_tag "customizations/maps" %>
<% end %>

app/views/pages/photos.html.erb
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="countdown-container">
          <p class="h1">Capture the Thrills!</p>
          <p class="text-faded">#BoulderBikeTour #bikerace</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="page-section clearfix">
  <div class="container">

    <div class="row mb-3 justify-content-between">
      <% if @page_id_prev.present? %>
        <%= link_to "Previous", photos_path(id: @page_id_prev), class: "btn btn-primary btn-xl ml-5 mr-2 col-lg-1 col-6" %>
      <% end %>
      <%= link_to "Next", photos_path(id: @page_id_next), class: "btn btn-primary btn-xl col-lg-1 col-6" %>
    </div>

    <% @photos.each_slice(6) do |photo1, photo2, photo3, photo4, photo5, photo6| %>
      <div class="row">
        <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
          <%= image_tag photo1, class: "w-100 shadow-1-strong rounded mb-4" %>
          <%= image_tag photo2, class: "w-100 shadow-1-strong rounded mb-4" %>
        </div>

        <div class="col-lg-4 mb-4 mb-lg-0">
          <%= image_tag photo3, class: "w-100 shadow-1-strong rounded mb-4" %>
          <%= image_tag photo4, class: "w-100 shadow-1-strong rounded mb-4" %>
        </div>

        <div class="col-lg-4 mb-4 mb-lg-0">
          <%= image_tag photo5, class: "w-100 shadow-1-strong rounded mb-4" %>
          <%= image_tag photo6, class: "w-100 shadow-1-strong rounded mb-4" %>
        </div>
      </div>
    <% end %>

    <div class="row mb-3 justify-content-between">
      <% if @page_id_prev.present? %>
        <%= link_to "Previous", photos_path(id: @page_id_prev), class: "btn btn-primary btn-xl ml-5 mr-2 col-lg-1 col-6" %>
      <% end %>
      <%= link_to "Next", photos_path(id: @page_id_next), class: "btn btn-primary btn-xl col-lg-1 col-6" %>
    </div>

  </div>
</section>

app/views/pages/thankyou.html.erb
<section class="page-section clearfix">
  <div class="container position-relative">
    <div class="position-absolute w-100 top-0 start-0">
    <%= render partial: "layouts/info_card", locals: {
      title_upper: 'Slogan submitted',
      title_lower: 'Thank you!',
      body_text: "Thank you for submitting your slogan for the Boulder Bike Race contest!<br>Your creative contribution means a lot to us. We'll review all the submissions carefully, and your slogan could be the one that captures the spirit of our event.<br>Stay tuned to see if your slogan makes it to the final round. In the meantime, keep pedaling and enjoying the ride!<br>Thank you again for being a part of the Boulder Bike Race community.",
      cta_btn_text: 'Track the team',
      cta_btn_link: locations_path
    } %>
  </div>
    <%= image_tag('thankyou.jpg', class: 'rounded w-100') %>
  </div>
</section>

app/views/riders/index.html.erb
<section class="page-section clearfix">
  <div class="container">
    <div class="row mb-3 justify-content-between row-gap-10">
      <% @riders.each do |rider| %>
          <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
            <%= render partial: "layouts/info_card", locals: {
              title_upper: "#{rider.fname} #{rider.lname}",
              body_text: "#{rider.city_origin} (#{rider.state_origin})",
              cta_btn_text: "Details",
              cta_btn_link: rider_path(rider),
              button_size: 's',
              btn_type: 'outline-primary'
            } %>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/riders/show.html.erb
<section class="page-section clearfix">
  <div class="container">
    <div class="row mb-3 justify-content-center">
        <%= render partial: "layouts/info_card", locals: {
          title_upper: "#{@rider.fname} #{@rider.lname}",
          body_text: "#{@rider.city_origin} (#{@rider.state_origin})",
        } %>
    </div>
  </div>
</section>